# Generated by Django 2.2.7 on 2019-12-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_sixth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='sex',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='salary',
            field=models.IntegerField(choices=[('male', 'txa'), ('gmale', 'axjik')], default='male'),
        ),
    ]
