# Generated by Django 2.2.7 on 2019-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_sixth', '0002_auto_20191208_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.BooleanField(choices=[('male', 'txa'), ('gmale', 'axjik')], default='male'),
        ),
    ]
