# Generated by Django 2.2.7 on 2019-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_sixth', '0003_auto_20191208_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.BooleanField(choices=[('txa', 'txa'), ('axjik', 'axjik')], default='txa'),
        ),
    ]
