# Generated by Django 2.2.7 on 2019-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия автора')),
                ('city', models.CharField(choices=[('kyiv', 'Киев'), ('chernigov', 'Чернигов'), ('odessa', 'Одесса'), ('lvov', 'Львов')], help_text='Выберите город со списка', max_length=200, verbose_name='Город')),
            ],
        ),
    ]
